// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: request.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CommonPagingMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonPagingMessage) Reset()         { *m = CommonPagingMessage{} }
func (m *CommonPagingMessage) String() string { return proto.CompactTextString(m) }
func (*CommonPagingMessage) ProtoMessage()    {}
func (*CommonPagingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{0}
}
func (m *CommonPagingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonPagingMessage.Unmarshal(m, b)
}
func (m *CommonPagingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonPagingMessage.Marshal(b, m, deterministic)
}
func (m *CommonPagingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonPagingMessage.Merge(m, src)
}
func (m *CommonPagingMessage) XXX_Size() int {
	return xxx_messageInfo_CommonPagingMessage.Size(m)
}
func (m *CommonPagingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonPagingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CommonPagingMessage proto.InternalMessageInfo

// user
type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	RefreshToken         string   `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Mac                  string   `protobuf:"bytes,4,opt,name=mac,proto3" json:"mac,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{1}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *LoginRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

// Location Service
type AddLocationRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Areas                []*Area  `protobuf:"bytes,3,rep,name=areas,proto3" json:"areas,omitempty"`
	LocationId           int32    `protobuf:"varint,4,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Status               Status   `protobuf:"varint,5,opt,name=status,proto3,enum=pb.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddLocationRequest) Reset()         { *m = AddLocationRequest{} }
func (m *AddLocationRequest) String() string { return proto.CompactTextString(m) }
func (*AddLocationRequest) ProtoMessage()    {}
func (*AddLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{2}
}
func (m *AddLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddLocationRequest.Unmarshal(m, b)
}
func (m *AddLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddLocationRequest.Marshal(b, m, deterministic)
}
func (m *AddLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddLocationRequest.Merge(m, src)
}
func (m *AddLocationRequest) XXX_Size() int {
	return xxx_messageInfo_AddLocationRequest.Size(m)
}
func (m *AddLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddLocationRequest proto.InternalMessageInfo

func (m *AddLocationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddLocationRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AddLocationRequest) GetAreas() []*Area {
	if m != nil {
		return m.Areas
	}
	return nil
}

func (m *AddLocationRequest) GetLocationId() int32 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

func (m *AddLocationRequest) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_activated
}

type ListLocationRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListLocationRequest) Reset()         { *m = ListLocationRequest{} }
func (m *ListLocationRequest) String() string { return proto.CompactTextString(m) }
func (*ListLocationRequest) ProtoMessage()    {}
func (*ListLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{3}
}
func (m *ListLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLocationRequest.Unmarshal(m, b)
}
func (m *ListLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLocationRequest.Marshal(b, m, deterministic)
}
func (m *ListLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLocationRequest.Merge(m, src)
}
func (m *ListLocationRequest) XXX_Size() int {
	return xxx_messageInfo_ListLocationRequest.Size(m)
}
func (m *ListLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListLocationRequest proto.InternalMessageInfo

func (m *ListLocationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListLocationRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type RemoveLocationRequest struct {
	LocationId           int32    `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveLocationRequest) Reset()         { *m = RemoveLocationRequest{} }
func (m *RemoveLocationRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveLocationRequest) ProtoMessage()    {}
func (*RemoveLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{4}
}
func (m *RemoveLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveLocationRequest.Unmarshal(m, b)
}
func (m *RemoveLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveLocationRequest.Marshal(b, m, deterministic)
}
func (m *RemoveLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveLocationRequest.Merge(m, src)
}
func (m *RemoveLocationRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveLocationRequest.Size(m)
}
func (m *RemoveLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveLocationRequest proto.InternalMessageInfo

func (m *RemoveLocationRequest) GetLocationId() int32 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

// Area service
type AddAreaRequest struct {
	LocationId           int32    `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAreaRequest) Reset()         { *m = AddAreaRequest{} }
func (m *AddAreaRequest) String() string { return proto.CompactTextString(m) }
func (*AddAreaRequest) ProtoMessage()    {}
func (*AddAreaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{5}
}
func (m *AddAreaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAreaRequest.Unmarshal(m, b)
}
func (m *AddAreaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAreaRequest.Marshal(b, m, deterministic)
}
func (m *AddAreaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAreaRequest.Merge(m, src)
}
func (m *AddAreaRequest) XXX_Size() int {
	return xxx_messageInfo_AddAreaRequest.Size(m)
}
func (m *AddAreaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAreaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddAreaRequest proto.InternalMessageInfo

func (m *AddAreaRequest) GetLocationId() int32 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

func (m *AddAreaRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListAreaRequest struct {
	LocationId           int32    `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAreaRequest) Reset()         { *m = ListAreaRequest{} }
func (m *ListAreaRequest) String() string { return proto.CompactTextString(m) }
func (*ListAreaRequest) ProtoMessage()    {}
func (*ListAreaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{6}
}
func (m *ListAreaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAreaRequest.Unmarshal(m, b)
}
func (m *ListAreaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAreaRequest.Marshal(b, m, deterministic)
}
func (m *ListAreaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAreaRequest.Merge(m, src)
}
func (m *ListAreaRequest) XXX_Size() int {
	return xxx_messageInfo_ListAreaRequest.Size(m)
}
func (m *ListAreaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAreaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAreaRequest proto.InternalMessageInfo

func (m *ListAreaRequest) GetLocationId() int32 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

type RemoveAreaRequest struct {
	LocationId           int32    `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	AreaId               int32    `protobuf:"varint,2,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveAreaRequest) Reset()         { *m = RemoveAreaRequest{} }
func (m *RemoveAreaRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveAreaRequest) ProtoMessage()    {}
func (*RemoveAreaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{7}
}
func (m *RemoveAreaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveAreaRequest.Unmarshal(m, b)
}
func (m *RemoveAreaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveAreaRequest.Marshal(b, m, deterministic)
}
func (m *RemoveAreaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveAreaRequest.Merge(m, src)
}
func (m *RemoveAreaRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveAreaRequest.Size(m)
}
func (m *RemoveAreaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveAreaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveAreaRequest proto.InternalMessageInfo

func (m *RemoveAreaRequest) GetLocationId() int32 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

func (m *RemoveAreaRequest) GetAreaId() int32 {
	if m != nil {
		return m.AreaId
	}
	return 0
}

// screen
type AddScreenRequest struct {
	MacAddress           string   `protobuf:"bytes,1,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	TypeOfDevice         string   `protobuf:"bytes,2,opt,name=type_of_device,json=typeOfDevice,proto3" json:"type_of_device,omitempty"`
	Os                   string   `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	AppVersion           string   `protobuf:"bytes,4,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddScreenRequest) Reset()         { *m = AddScreenRequest{} }
func (m *AddScreenRequest) String() string { return proto.CompactTextString(m) }
func (*AddScreenRequest) ProtoMessage()    {}
func (*AddScreenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{8}
}
func (m *AddScreenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddScreenRequest.Unmarshal(m, b)
}
func (m *AddScreenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddScreenRequest.Marshal(b, m, deterministic)
}
func (m *AddScreenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddScreenRequest.Merge(m, src)
}
func (m *AddScreenRequest) XXX_Size() int {
	return xxx_messageInfo_AddScreenRequest.Size(m)
}
func (m *AddScreenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddScreenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddScreenRequest proto.InternalMessageInfo

func (m *AddScreenRequest) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *AddScreenRequest) GetTypeOfDevice() string {
	if m != nil {
		return m.TypeOfDevice
	}
	return ""
}

func (m *AddScreenRequest) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *AddScreenRequest) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

type ListScreenRequest struct {
	LocationId           int32    `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	AreaId               int32    `protobuf:"varint,2,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListScreenRequest) Reset()         { *m = ListScreenRequest{} }
func (m *ListScreenRequest) String() string { return proto.CompactTextString(m) }
func (*ListScreenRequest) ProtoMessage()    {}
func (*ListScreenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{9}
}
func (m *ListScreenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListScreenRequest.Unmarshal(m, b)
}
func (m *ListScreenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListScreenRequest.Marshal(b, m, deterministic)
}
func (m *ListScreenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListScreenRequest.Merge(m, src)
}
func (m *ListScreenRequest) XXX_Size() int {
	return xxx_messageInfo_ListScreenRequest.Size(m)
}
func (m *ListScreenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListScreenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListScreenRequest proto.InternalMessageInfo

func (m *ListScreenRequest) GetLocationId() int32 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

func (m *ListScreenRequest) GetAreaId() int32 {
	if m != nil {
		return m.AreaId
	}
	return 0
}

type UpdateScreenRequest struct {
	Data                 *ScreenInfo `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateScreenRequest) Reset()         { *m = UpdateScreenRequest{} }
func (m *UpdateScreenRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateScreenRequest) ProtoMessage()    {}
func (*UpdateScreenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{10}
}
func (m *UpdateScreenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateScreenRequest.Unmarshal(m, b)
}
func (m *UpdateScreenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateScreenRequest.Marshal(b, m, deterministic)
}
func (m *UpdateScreenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateScreenRequest.Merge(m, src)
}
func (m *UpdateScreenRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateScreenRequest.Size(m)
}
func (m *UpdateScreenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateScreenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateScreenRequest proto.InternalMessageInfo

func (m *UpdateScreenRequest) GetData() *ScreenInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

// activities
type ListActivitiesRequest struct {
	ScreenId             int32    `protobuf:"varint,1,opt,name=screen_id,json=screenId,proto3" json:"screen_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListActivitiesRequest) Reset()         { *m = ListActivitiesRequest{} }
func (m *ListActivitiesRequest) String() string { return proto.CompactTextString(m) }
func (*ListActivitiesRequest) ProtoMessage()    {}
func (*ListActivitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{11}
}
func (m *ListActivitiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListActivitiesRequest.Unmarshal(m, b)
}
func (m *ListActivitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListActivitiesRequest.Marshal(b, m, deterministic)
}
func (m *ListActivitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListActivitiesRequest.Merge(m, src)
}
func (m *ListActivitiesRequest) XXX_Size() int {
	return xxx_messageInfo_ListActivitiesRequest.Size(m)
}
func (m *ListActivitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListActivitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListActivitiesRequest proto.InternalMessageInfo

func (m *ListActivitiesRequest) GetScreenId() int32 {
	if m != nil {
		return m.ScreenId
	}
	return 0
}

// issue
type ReportIssueRequest struct {
	ScreenId             int32    `protobuf:"varint,1,opt,name=screen_id,json=screenId,proto3" json:"screen_id,omitempty"`
	IssueType            int32    `protobuf:"varint,2,opt,name=issue_type,json=issueType,proto3" json:"issue_type,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportIssueRequest) Reset()         { *m = ReportIssueRequest{} }
func (m *ReportIssueRequest) String() string { return proto.CompactTextString(m) }
func (*ReportIssueRequest) ProtoMessage()    {}
func (*ReportIssueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{12}
}
func (m *ReportIssueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportIssueRequest.Unmarshal(m, b)
}
func (m *ReportIssueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportIssueRequest.Marshal(b, m, deterministic)
}
func (m *ReportIssueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportIssueRequest.Merge(m, src)
}
func (m *ReportIssueRequest) XXX_Size() int {
	return xxx_messageInfo_ReportIssueRequest.Size(m)
}
func (m *ReportIssueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportIssueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportIssueRequest proto.InternalMessageInfo

func (m *ReportIssueRequest) GetScreenId() int32 {
	if m != nil {
		return m.ScreenId
	}
	return 0
}

func (m *ReportIssueRequest) GetIssueType() int32 {
	if m != nil {
		return m.IssueType
	}
	return 0
}

func (m *ReportIssueRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// video
type GetVideoRequest struct {
	VideoId              int32    `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVideoRequest) Reset()         { *m = GetVideoRequest{} }
func (m *GetVideoRequest) String() string { return proto.CompactTextString(m) }
func (*GetVideoRequest) ProtoMessage()    {}
func (*GetVideoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{13}
}
func (m *GetVideoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVideoRequest.Unmarshal(m, b)
}
func (m *GetVideoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVideoRequest.Marshal(b, m, deterministic)
}
func (m *GetVideoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVideoRequest.Merge(m, src)
}
func (m *GetVideoRequest) XXX_Size() int {
	return xxx_messageInfo_GetVideoRequest.Size(m)
}
func (m *GetVideoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVideoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVideoRequest proto.InternalMessageInfo

func (m *GetVideoRequest) GetVideoId() int32 {
	if m != nil {
		return m.VideoId
	}
	return 0
}

// campaign
type CampaignRequest struct {
	CampaignId           int32    `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CampaignRequest) Reset()         { *m = CampaignRequest{} }
func (m *CampaignRequest) String() string { return proto.CompactTextString(m) }
func (*CampaignRequest) ProtoMessage()    {}
func (*CampaignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{14}
}
func (m *CampaignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CampaignRequest.Unmarshal(m, b)
}
func (m *CampaignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CampaignRequest.Marshal(b, m, deterministic)
}
func (m *CampaignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CampaignRequest.Merge(m, src)
}
func (m *CampaignRequest) XXX_Size() int {
	return xxx_messageInfo_CampaignRequest.Size(m)
}
func (m *CampaignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CampaignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CampaignRequest proto.InternalMessageInfo

func (m *CampaignRequest) GetCampaignId() int32 {
	if m != nil {
		return m.CampaignId
	}
	return 0
}

func init() {
	proto.RegisterType((*CommonPagingMessage)(nil), "pb.CommonPagingMessage")
	proto.RegisterType((*LoginRequest)(nil), "pb.LoginRequest")
	proto.RegisterType((*AddLocationRequest)(nil), "pb.AddLocationRequest")
	proto.RegisterType((*ListLocationRequest)(nil), "pb.ListLocationRequest")
	proto.RegisterType((*RemoveLocationRequest)(nil), "pb.RemoveLocationRequest")
	proto.RegisterType((*AddAreaRequest)(nil), "pb.AddAreaRequest")
	proto.RegisterType((*ListAreaRequest)(nil), "pb.ListAreaRequest")
	proto.RegisterType((*RemoveAreaRequest)(nil), "pb.RemoveAreaRequest")
	proto.RegisterType((*AddScreenRequest)(nil), "pb.AddScreenRequest")
	proto.RegisterType((*ListScreenRequest)(nil), "pb.ListScreenRequest")
	proto.RegisterType((*UpdateScreenRequest)(nil), "pb.UpdateScreenRequest")
	proto.RegisterType((*ListActivitiesRequest)(nil), "pb.ListActivitiesRequest")
	proto.RegisterType((*ReportIssueRequest)(nil), "pb.ReportIssueRequest")
	proto.RegisterType((*GetVideoRequest)(nil), "pb.GetVideoRequest")
	proto.RegisterType((*CampaignRequest)(nil), "pb.CampaignRequest")
}

func init() { proto.RegisterFile("request.proto", fileDescriptor_7f73548e33e655fe) }

var fileDescriptor_7f73548e33e655fe = []byte{
	// 563 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x95, 0x9d, 0x34, 0x4d, 0x6f, 0xfa, 0xa5, 0xfd, 0x26, 0x8a, 0x30, 0x45, 0x40, 0x34, 0xb0,
	0xc8, 0x02, 0x65, 0x11, 0x58, 0x80, 0x58, 0x85, 0x80, 0x90, 0xa5, 0x54, 0x20, 0xb7, 0x74, 0xc1,
	0xc6, 0x9a, 0x78, 0x6e, 0xc2, 0x08, 0xec, 0x19, 0x66, 0x26, 0x41, 0x5d, 0xf0, 0x02, 0xbc, 0x08,
	0xaf, 0x89, 0x66, 0x6c, 0x27, 0x21, 0x6c, 0x5a, 0xd8, 0xf9, 0x9e, 0xfb, 0x77, 0xce, 0x99, 0x2b,
	0xc3, 0x7f, 0x1a, 0xbf, 0xae, 0xd0, 0xd8, 0x91, 0xd2, 0xd2, 0x4a, 0x12, 0xaa, 0xf9, 0x59, 0xc7,
	0x5e, 0x2b, 0x34, 0x25, 0x40, 0xfb, 0xd0, 0x9b, 0xca, 0x3c, 0x97, 0xc5, 0x7b, 0xb6, 0x14, 0xc5,
	0xf2, 0x1c, 0x8d, 0x61, 0x4b, 0xa4, 0xdf, 0xe1, 0x78, 0x26, 0x97, 0xa2, 0x48, 0xca, 0x6e, 0x72,
	0x06, 0xed, 0x95, 0x41, 0x5d, 0xb0, 0x1c, 0xa3, 0x60, 0x10, 0x0c, 0x8f, 0x92, 0x4d, 0xec, 0x72,
	0x8a, 0x19, 0xf3, 0x4d, 0x6a, 0x1e, 0x85, 0x65, 0xae, 0x8e, 0xc9, 0x23, 0x47, 0x60, 0xa1, 0xd1,
	0x7c, 0x4a, 0xad, 0xfc, 0x8c, 0x45, 0xd4, 0xf0, 0x05, 0xc7, 0x15, 0x78, 0xe9, 0x30, 0x72, 0x0a,
	0x8d, 0x9c, 0x65, 0x51, 0xd3, 0xa7, 0xdc, 0x27, 0xfd, 0x19, 0x00, 0x99, 0x70, 0x3e, 0x93, 0x19,
	0xb3, 0x42, 0x6e, 0x58, 0x10, 0x68, 0xee, 0x30, 0xf0, 0xdf, 0x24, 0x82, 0x43, 0xc6, 0xb9, 0x46,
	0x63, 0xaa, 0xe5, 0x75, 0x48, 0x1e, 0xc0, 0x01, 0xd3, 0xc8, 0x4c, 0xd4, 0x18, 0x34, 0x86, 0x9d,
	0x71, 0x7b, 0xa4, 0xe6, 0xa3, 0x89, 0x46, 0x96, 0x94, 0x30, 0x79, 0x08, 0x9d, 0x2f, 0xd5, 0x82,
	0x54, 0x70, 0xbf, 0xfe, 0x20, 0x81, 0x1a, 0x8a, 0x39, 0xa1, 0xd0, 0x32, 0x96, 0xd9, 0x95, 0x89,
	0x0e, 0x06, 0xc1, 0xb0, 0x3b, 0x06, 0x37, 0xe1, 0xc2, 0x23, 0x49, 0x95, 0xa1, 0x53, 0xe8, 0xcd,
	0x84, 0xb1, 0xff, 0xc4, 0x94, 0x3e, 0x87, 0x7e, 0x82, 0xb9, 0x5c, 0xe3, 0xfe, 0x98, 0x3d, 0x8a,
	0xc1, 0x3e, 0x45, 0xfa, 0x06, 0xba, 0x13, 0xce, 0xbd, 0xaa, 0x1b, 0xb6, 0x6c, 0xa8, 0x85, 0x5b,
	0x6a, 0x74, 0x0c, 0x27, 0x4e, 0xc5, 0x6d, 0xe6, 0xd0, 0x73, 0xf8, 0xbf, 0x24, 0x7d, 0xab, 0xed,
	0x77, 0xe0, 0xd0, 0xb9, 0xef, 0x92, 0xa1, 0x4f, 0xb6, 0x5c, 0x18, 0x73, 0xfa, 0x23, 0x80, 0xd3,
	0x09, 0xe7, 0x17, 0x99, 0x46, 0xdc, 0xd5, 0x9f, 0xb3, 0x2c, 0xad, 0x6d, 0x2b, 0xdd, 0x84, 0x9c,
	0x65, 0x93, 0xea, 0x8d, 0x1f, 0x43, 0xd7, 0x5d, 0x73, 0x2a, 0x17, 0x29, 0xc7, 0xb5, 0xc8, 0x6a,
	0x59, 0xc7, 0x0e, 0x7d, 0xb7, 0x78, 0xed, 0x31, 0xd2, 0x85, 0x50, 0x9a, 0xea, 0xf4, 0x42, 0xe9,
	0x5f, 0x9e, 0x29, 0x95, 0xae, 0x51, 0x1b, 0x21, 0x8b, 0xea, 0xf0, 0x80, 0x29, 0x75, 0x55, 0x22,
	0x4e, 0x9b, 0xf3, 0xe3, 0x0f, 0x32, 0x7f, 0xa9, 0xed, 0x05, 0xf4, 0x3e, 0x28, 0xce, 0x2c, 0xfe,
	0x3e, 0x90, 0x42, 0x93, 0x33, 0xcb, 0xfc, 0xa4, 0xce, 0xb8, 0xeb, 0xaf, 0xcb, 0x17, 0xc4, 0xc5,
	0x42, 0x26, 0x3e, 0x47, 0x9f, 0x41, 0xdf, 0xbf, 0x4c, 0x66, 0xc5, 0x5a, 0x58, 0x81, 0xa6, 0x6e,
	0xbe, 0x07, 0x47, 0xc6, 0x17, 0x6f, 0xb9, 0xb4, 0x4b, 0x20, 0xe6, 0x54, 0x03, 0x49, 0x50, 0x49,
	0x6d, 0x63, 0x63, 0x56, 0x78, 0x93, 0x16, 0x72, 0x1f, 0x40, 0xb8, 0xe2, 0xd4, 0x39, 0x57, 0xf1,
	0x3f, 0xf2, 0xc8, 0xe5, 0xb5, 0x42, 0x32, 0x80, 0x0e, 0x47, 0x93, 0x69, 0xa1, 0x9c, 0xd8, 0xca,
	0xcb, 0x5d, 0x88, 0x3e, 0x81, 0x93, 0xb7, 0x68, 0xaf, 0x04, 0x47, 0x59, 0x2f, 0xbc, 0x0b, 0xed,
	0xb5, 0x8b, 0xb7, 0xfb, 0x0e, 0x7d, 0x1c, 0x73, 0x77, 0x71, 0x53, 0x96, 0x2b, 0x26, 0x96, 0xbb,
	0xfe, 0x66, 0x15, 0xb4, 0xe3, 0x6f, 0x0d, 0xc5, 0xfc, 0x55, 0xeb, 0x63, 0x73, 0xf4, 0x52, 0xcd,
	0xe7, 0x2d, 0xff, 0xeb, 0x7a, 0xfa, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x4b, 0x1a, 0xa5, 0xdc,
	0x04, 0x00, 0x00,
}
