// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: request.proto

package pb

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *CommonPagingMessage) Validate() error {
	return nil
}
func (this *LoginRequest) Validate() error {
	return nil
}
func (this *AddLocationRequest) Validate() error {
	for _, item := range this.Areas {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Areas", err)
			}
		}
	}
	return nil
}
func (this *ListLocationRequest) Validate() error {
	return nil
}
func (this *RemoveLocationRequest) Validate() error {
	return nil
}
func (this *AddAreaRequest) Validate() error {
	return nil
}
func (this *ListAreaRequest) Validate() error {
	return nil
}
func (this *RemoveAreaRequest) Validate() error {
	return nil
}
func (this *AddScreenRequest) Validate() error {
	return nil
}
func (this *ListScreenRequest) Validate() error {
	return nil
}
func (this *UpdateScreenRequest) Validate() error {
	if this.Data != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Data); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
		}
	}
	return nil
}
func (this *ListActivitiesRequest) Validate() error {
	return nil
}
func (this *ReportIssueRequest) Validate() error {
	return nil
}
func (this *GetVideoRequest) Validate() error {
	return nil
}
func (this *CampaignRequest) Validate() error {
	return nil
}
