// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: service.proto

package pb

import (
	bytes "bytes"
	context "context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type VersionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionRequest) Reset()         { *m = VersionRequest{} }
func (m *VersionRequest) String() string { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()    {}
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}
func (m *VersionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VersionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionRequest.Merge(m, src)
}
func (m *VersionRequest) XXX_Size() int {
	return m.Size()
}
func (m *VersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VersionRequest proto.InternalMessageInfo

type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}
func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return m.Size()
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LivenessRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LivenessRequest) Reset()         { *m = LivenessRequest{} }
func (m *LivenessRequest) String() string { return proto.CompactTextString(m) }
func (*LivenessRequest) ProtoMessage()    {}
func (*LivenessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}
func (m *LivenessRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LivenessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LivenessRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LivenessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LivenessRequest.Merge(m, src)
}
func (m *LivenessRequest) XXX_Size() int {
	return m.Size()
}
func (m *LivenessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LivenessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LivenessRequest proto.InternalMessageInfo

type LivenessResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LivenessResponse) Reset()         { *m = LivenessResponse{} }
func (m *LivenessResponse) String() string { return proto.CompactTextString(m) }
func (*LivenessResponse) ProtoMessage()    {}
func (*LivenessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}
func (m *LivenessResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LivenessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LivenessResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LivenessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LivenessResponse.Merge(m, src)
}
func (m *LivenessResponse) XXX_Size() int {
	return m.Size()
}
func (m *LivenessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LivenessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LivenessResponse proto.InternalMessageInfo

func (m *LivenessResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ToggleReadinessRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToggleReadinessRequest) Reset()         { *m = ToggleReadinessRequest{} }
func (m *ToggleReadinessRequest) String() string { return proto.CompactTextString(m) }
func (*ToggleReadinessRequest) ProtoMessage()    {}
func (*ToggleReadinessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}
func (m *ToggleReadinessRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ToggleReadinessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ToggleReadinessRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ToggleReadinessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToggleReadinessRequest.Merge(m, src)
}
func (m *ToggleReadinessRequest) XXX_Size() int {
	return m.Size()
}
func (m *ToggleReadinessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ToggleReadinessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ToggleReadinessRequest proto.InternalMessageInfo

type ToggleReadinessResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToggleReadinessResponse) Reset()         { *m = ToggleReadinessResponse{} }
func (m *ToggleReadinessResponse) String() string { return proto.CompactTextString(m) }
func (*ToggleReadinessResponse) ProtoMessage()    {}
func (*ToggleReadinessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}
func (m *ToggleReadinessResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ToggleReadinessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ToggleReadinessResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ToggleReadinessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToggleReadinessResponse.Merge(m, src)
}
func (m *ToggleReadinessResponse) XXX_Size() int {
	return m.Size()
}
func (m *ToggleReadinessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ToggleReadinessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ToggleReadinessResponse proto.InternalMessageInfo

func (m *ToggleReadinessResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ReadinessRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadinessRequest) Reset()         { *m = ReadinessRequest{} }
func (m *ReadinessRequest) String() string { return proto.CompactTextString(m) }
func (*ReadinessRequest) ProtoMessage()    {}
func (*ReadinessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}
func (m *ReadinessRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReadinessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReadinessRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReadinessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadinessRequest.Merge(m, src)
}
func (m *ReadinessRequest) XXX_Size() int {
	return m.Size()
}
func (m *ReadinessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadinessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadinessRequest proto.InternalMessageInfo

type ReadinessResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadinessResponse) Reset()         { *m = ReadinessResponse{} }
func (m *ReadinessResponse) String() string { return proto.CompactTextString(m) }
func (*ReadinessResponse) ProtoMessage()    {}
func (*ReadinessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}
func (m *ReadinessResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReadinessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReadinessResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReadinessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadinessResponse.Merge(m, src)
}
func (m *ReadinessResponse) XXX_Size() int {
	return m.Size()
}
func (m *ReadinessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadinessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadinessResponse proto.InternalMessageInfo

func (m *ReadinessResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionRequest)(nil), "pb.VersionRequest")
	proto.RegisterType((*VersionResponse)(nil), "pb.VersionResponse")
	proto.RegisterType((*LivenessRequest)(nil), "pb.LivenessRequest")
	proto.RegisterType((*LivenessResponse)(nil), "pb.LivenessResponse")
	proto.RegisterType((*ToggleReadinessRequest)(nil), "pb.ToggleReadinessRequest")
	proto.RegisterType((*ToggleReadinessResponse)(nil), "pb.ToggleReadinessResponse")
	proto.RegisterType((*ReadinessRequest)(nil), "pb.ReadinessRequest")
	proto.RegisterType((*ReadinessResponse)(nil), "pb.ReadinessResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 853 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x96, 0xdf, 0x6e, 0xe3, 0x44,
	0x14, 0xc6, 0x95, 0x95, 0xb6, 0x4d, 0x4e, 0x12, 0x27, 0x99, 0x6e, 0xdb, 0x60, 0x50, 0x85, 0x7c,
	0x85, 0x04, 0x5b, 0x4b, 0xec, 0x2d, 0x37, 0x61, 0xbb, 0x94, 0x5d, 0xa5, 0xa2, 0x64, 0xc9, 0x4a,
	0x20, 0x6e, 0x26, 0xf1, 0x59, 0x77, 0x24, 0xc7, 0x63, 0x3c, 0x93, 0x48, 0xbd, 0xe5, 0x15, 0x78,
	0x09, 0x2e, 0x79, 0x0c, 0x2e, 0x91, 0x78, 0x01, 0x54, 0xf1, 0x20, 0xc8, 0x67, 0x66, 0x62, 0x3b,
	0x36, 0x0b, 0x7b, 0xe7, 0xf9, 0xe6, 0x7c, 0xbf, 0x9c, 0x7f, 0xb6, 0x02, 0x43, 0x85, 0xf9, 0x4e,
	0xac, 0xf1, 0x32, 0xcb, 0xa5, 0x96, 0xec, 0x51, 0xb6, 0xf2, 0x3f, 0x8a, 0xa5, 0x8c, 0x13, 0x0c,
	0x79, 0x26, 0x42, 0x9e, 0xa6, 0x52, 0x73, 0x2d, 0x64, 0xaa, 0x4c, 0x84, 0xff, 0x34, 0x16, 0xfa,
	0x6e, 0xbb, 0xba, 0x5c, 0xcb, 0x4d, 0x18, 0xcb, 0x58, 0x86, 0x24, 0xaf, 0xb6, 0x6f, 0xe9, 0x44,
	0x07, 0x7a, 0xb2, 0xe1, 0xc3, 0x1c, 0x7f, 0xda, 0xa2, 0xd2, 0xf6, 0xe8, 0xe5, 0xa8, 0x32, 0x99,
	0x2a, 0xfb, 0x7b, 0x7e, 0x5f, 0xdf, 0x67, 0x68, 0xd1, 0xc1, 0x18, 0xbc, 0x37, 0x98, 0x2b, 0x21,
	0xd3, 0x85, 0x31, 0x05, 0x9f, 0xc2, 0x68, 0xaf, 0x18, 0x1f, 0x9b, 0xc2, 0xf1, 0xce, 0x48, 0xd3,
	0xce, 0xc7, 0x9d, 0x4f, 0x7a, 0x0b, 0x77, 0x0c, 0x26, 0x30, 0x9a, 0x8b, 0x1d, 0xa6, 0xa8, 0x94,
	0xf3, 0x7f, 0x06, 0xe3, 0x52, 0x2a, 0x01, 0x1b, 0x54, 0x8a, 0xc7, 0xe8, 0x00, 0xf6, 0x18, 0x4c,
	0xe1, 0xec, 0x3b, 0x19, 0xc7, 0x09, 0x2e, 0x90, 0x47, 0xa2, 0xca, 0x79, 0x06, 0xe7, 0x8d, 0x9b,
	0xff, 0xc4, 0x31, 0x18, 0x37, 0x40, 0x4f, 0x61, 0xf2, 0x1e, 0x88, 0xcf, 0x7f, 0xf3, 0xe0, 0x68,
	0x16, 0x25, 0x62, 0x87, 0xec, 0x0a, 0x8e, 0x6d, 0x2b, 0x18, 0xbb, 0xcc, 0x56, 0x97, 0xf5, 0x4e,
	0xf9, 0x27, 0x35, 0xcd, 0x80, 0x83, 0xf1, 0xcf, 0x7f, 0xfe, 0xfd, 0xcb, 0x23, 0x60, 0xdd, 0xd0,
	0xf6, 0x88, 0x7d, 0x05, 0x5d, 0xd7, 0x10, 0x46, 0x96, 0x83, 0x8e, 0xf9, 0x4f, 0xea, 0xa2, 0x05,
	0x8d, 0x08, 0xd4, 0x63, 0xc7, 0xe1, 0x1d, 0xf2, 0x44, 0xdf, 0xb1, 0x1f, 0x60, 0x74, 0xd0, 0x10,
	0xe6, 0x17, 0xce, 0xf6, 0xfe, 0xf9, 0x1f, 0xb6, 0xde, 0x59, 0xb8, 0x47, 0xf0, 0x6e, 0x70, 0x14,
	0xe6, 0xc8, 0xa3, 0x7b, 0xf6, 0x35, 0xf4, 0x4a, 0x2a, 0xe5, 0xd3, 0xe0, 0x9d, 0x1e, 0xa8, 0x75,
	0x12, 0x73, 0xa4, 0x2f, 0xe0, 0xf1, 0x5c, 0xc6, 0x22, 0x65, 0x63, 0xaa, 0xaa, 0x78, 0x74, 0x84,
	0x49, 0x45, 0x69, 0xe4, 0x91, 0x90, 0xe9, 0x16, 0xbc, 0x6b, 0xd4, 0x4b, 0x85, 0xf9, 0x6d, 0x2e,
	0xdf, 0x8a, 0x04, 0x0d, 0xe6, 0xc5, 0x26, 0xd3, 0xf7, 0x37, 0x66, 0x40, 0x3e, 0x15, 0x5d, 0x8f,
	0x6a, 0xe9, 0x7e, 0x66, 0xfd, 0xaf, 0x60, 0xb2, 0xcc, 0x22, 0xae, 0xb1, 0x0a, 0x1d, 0x15, 0x88,
	0x8a, 0xe0, 0xd3, 0x78, 0x9f, 0xcb, 0xcd, 0xa6, 0x39, 0x49, 0xbf, 0x64, 0x2d, 0xa1, 0x3f, 0x8b,
	0xa2, 0xb9, 0x5c, 0xd3, 0xdb, 0xc9, 0xce, 0x0a, 0x53, 0x45, 0x70, 0x75, 0x9e, 0x37, 0x74, 0x4b,
	0x3c, 0x25, 0xe2, 0x28, 0x18, 0x86, 0x89, 0xbd, 0x0a, 0x79, 0x14, 0xb1, 0x6f, 0xa1, 0xe7, 0x42,
	0x15, 0x3b, 0x2f, 0x33, 0xb9, 0xe5, 0xb1, 0x48, 0x63, 0x57, 0xf6, 0xd4, 0x6c, 0x89, 0xd2, 0x0d,
	0xec, 0x84, 0xb0, 0xfd, 0xa0, 0xb7, 0xc7, 0xb2, 0xef, 0xc1, 0x5b, 0xe0, 0x46, 0xee, 0x70, 0x9f,
	0xec, 0x07, 0x66, 0x7c, 0x55, 0xcd, 0xe5, 0xdb, 0x56, 0xfc, 0x94, 0x98, 0x2c, 0x18, 0x97, 0xa9,
	0xe6, 0x64, 0x66, 0x57, 0xc5, 0x3a, 0x2b, 0x3d, 0xcb, 0x91, 0xbb, 0x75, 0x36, 0xa7, 0x83, 0x75,
	0x76, 0xa2, 0x05, 0x0e, 0x09, 0x78, 0x1c, 0x3c, 0x0e, 0x79, 0xe1, 0xbc, 0x01, 0x30, 0xc9, 0x10,
	0xe7, 0xb4, 0x4c, 0xae, 0x4a, 0x6a, 0x4b, 0xec, 0x09, 0x71, 0xbc, 0x60, 0x40, 0x1c, 0x97, 0xd4,
	0x0d, 0xf4, 0x66, 0x51, 0xf4, 0x7a, 0x9d, 0x23, 0xa6, 0x66, 0x7f, 0xf7, 0xc7, 0xda, 0xfe, 0x56,
	0x54, 0xcb, 0x3b, 0x21, 0xde, 0x90, 0xf5, 0x43, 0x45, 0x17, 0x34, 0x91, 0xd7, 0x30, 0x30, 0x4b,
	0x63, 0x89, 0x34, 0x94, 0xaa, 0xf2, 0xae, 0x0c, 0xcf, 0x88, 0x38, 0x0e, 0x3c, 0x47, 0xdc, 0x92,
	0x91, 0xcd, 0x01, 0x8a, 0xae, 0x58, 0xe4, 0xa9, 0xeb, 0x52, 0x1d, 0x78, 0x76, 0x28, 0xd7, 0xbf,
	0x06, 0xc1, 0xb1, 0x85, 0xb2, 0x1f, 0xc1, 0xa3, 0x1e, 0xaf, 0xb5, 0xd8, 0x09, 0x2d, 0x50, 0x99,
	0x09, 0xd7, 0x35, 0x47, 0xf5, 0xdb, 0xae, 0xea, 0x0d, 0x08, 0xfa, 0x21, 0x2f, 0x59, 0x37, 0xd0,
	0x9d, 0x45, 0xd1, 0x4b, 0xa5, 0xb6, 0x68, 0xd6, 0x7c, 0x81, 0x99, 0xcc, 0x35, 0x09, 0xef, 0xaa,
	0xbd, 0xdc, 0x70, 0x5b, 0xbb, 0x20, 0xc4, 0x1c, 0x7a, 0xc5, 0xaf, 0xbf, 0x11, 0x11, 0xca, 0x7f,
	0xdf, 0xf0, 0x7d, 0x4b, 0x28, 0xae, 0xa5, 0xf4, 0x5d, 0xa1, 0x2b, 0xf6, 0x0a, 0xba, 0xd7, 0x68,
	0x61, 0x27, 0xf6, 0x63, 0x60, 0x2d, 0x95, 0x0d, 0x2c, 0xc5, 0x46, 0xa1, 0x86, 0x13, 0xc6, 0xa8,
	0xd9, 0x4b, 0xe8, 0x2f, 0xb3, 0x44, 0xf2, 0xc8, 0xe0, 0x7a, 0xf4, 0x49, 0x2f, 0x1e, 0x7d, 0x3b,
	0xf3, 0xfd, 0x5d, 0xcb, 0x7c, 0x2d, 0x67, 0x4b, 0x41, 0x6c, 0x09, 0x83, 0x22, 0xf9, 0xe7, 0x7c,
	0x93, 0x71, 0x11, 0xa7, 0xff, 0xe3, 0x4d, 0x76, 0xa1, 0x7b, 0x34, 0x23, 0xf4, 0x20, 0x80, 0x70,
	0x6d, 0xaf, 0x14, 0xbb, 0x85, 0xfe, 0x35, 0x96, 0x54, 0x2a, 0xb8, 0x34, 0x56, 0x0a, 0x6e, 0xd0,
	0xca, 0x44, 0xf7, 0x34, 0xaa, 0xf9, 0x1b, 0x18, 0xbc, 0x88, 0x44, 0x89, 0x64, 0x55, 0xf7, 0x15,
	0x6a, 0x2e, 0x92, 0xd6, 0xe1, 0x9e, 0x13, 0x6f, 0x12, 0x8c, 0x2a, 0x3c, 0x8c, 0x84, 0xfe, 0x72,
	0xfc, 0xeb, 0xc3, 0x45, 0xe7, 0xf7, 0x87, 0x8b, 0xce, 0x1f, 0x0f, 0x17, 0x9d, 0xbf, 0x1e, 0x2e,
	0x3a, 0xab, 0x23, 0xfa, 0x77, 0xf1, 0xec, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x2b, 0x82,
	0x11, 0xeb, 0x08, 0x00, 0x00,
}

func (this *VersionRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*VersionRequest)
	if !ok {
		that2, ok := that.(VersionRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *VersionResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*VersionResponse)
	if !ok {
		that2, ok := that.(VersionResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Version != that1.Version {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *LivenessRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LivenessRequest)
	if !ok {
		that2, ok := that.(LivenessRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *LivenessResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LivenessResponse)
	if !ok {
		that2, ok := that.(LivenessResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Message != that1.Message {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *ToggleReadinessRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ToggleReadinessRequest)
	if !ok {
		that2, ok := that.(ToggleReadinessRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *ToggleReadinessResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ToggleReadinessResponse)
	if !ok {
		that2, ok := that.(ToggleReadinessResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Message != that1.Message {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *ReadinessRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ReadinessRequest)
	if !ok {
		that2, ok := that.(ReadinessRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *ReadinessResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ReadinessResponse)
	if !ok {
		that2, ok := that.(ReadinessResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Message != that1.Message {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdliveClient is the client API for Adlive service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdliveClient interface {
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
	Liveness(ctx context.Context, in *LivenessRequest, opts ...grpc.CallOption) (*LivenessResponse, error)
	ToggleReadiness(ctx context.Context, in *ToggleReadinessRequest, opts ...grpc.CallOption) (*ToggleReadinessResponse, error)
	Readiness(ctx context.Context, in *ReadinessRequest, opts ...grpc.CallOption) (*ReadinessResponse, error)
	// service: user
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	GetUserProfile(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*GetUserProfileResponse, error)
	UpdateUserProfile(ctx context.Context, in *UserProfile, opts ...grpc.CallOption) (*CommonResponse, error)
	// service: location
	AddLocation(ctx context.Context, in *AddLocationRequest, opts ...grpc.CallOption) (*AddLocationResponse, error)
	Locations(ctx context.Context, in *CommonPagingMessage, opts ...grpc.CallOption) (*ListLocationResponse, error)
	RemoveLocation(ctx context.Context, in *RemoveLocationRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	// service: area
	ListArea(ctx context.Context, in *ListAreaRequest, opts ...grpc.CallOption) (*ListAreaResponse, error)
	RemoveArea(ctx context.Context, in *RemoveAreaRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	// service: manageScreen
	AddScreen(ctx context.Context, in *AddScreenRequest, opts ...grpc.CallOption) (*AddScreenResponse, error)
	UpdateScreen(ctx context.Context, in *UpdateScreenRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	ListScreen(ctx context.Context, in *ListScreenRequest, opts ...grpc.CallOption) (*ListScreenResponse, error)
	// service: activities
	ListActivities(ctx context.Context, in *ListActivitiesRequest, opts ...grpc.CallOption) (*ListActivitiesResponse, error)
	// service: Issue
	AddIssue(ctx context.Context, in *ReportIssueRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	// service: manageVideo
	ListVideo(ctx context.Context, in *CommonPagingMessage, opts ...grpc.CallOption) (*ListVideoResponse, error)
	GetVideo(ctx context.Context, in *GetVideoRequest, opts ...grpc.CallOption) (*GetVideoResponse, error)
	UploadVideo(ctx context.Context, in *Video, opts ...grpc.CallOption) (*UploadVideoResponse, error)
	// service: Campaign
	ListCampaign(ctx context.Context, in *CommonPagingMessage, opts ...grpc.CallOption) (*ListCampaignResponse, error)
	GetCampaign(ctx context.Context, in *CampaignRequest, opts ...grpc.CallOption) (*CampaignResponse, error)
	EditCampaign(ctx context.Context, in *CampaignDetail, opts ...grpc.CallOption) (*CommonResponse, error)
}

type adliveClient struct {
	cc *grpc.ClientConn
}

func NewAdliveClient(cc *grpc.ClientConn) AdliveClient {
	return &adliveClient{cc}
}

func (c *adliveClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adliveClient) Liveness(ctx context.Context, in *LivenessRequest, opts ...grpc.CallOption) (*LivenessResponse, error) {
	out := new(LivenessResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/Liveness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adliveClient) ToggleReadiness(ctx context.Context, in *ToggleReadinessRequest, opts ...grpc.CallOption) (*ToggleReadinessResponse, error) {
	out := new(ToggleReadinessResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/ToggleReadiness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adliveClient) Readiness(ctx context.Context, in *ReadinessRequest, opts ...grpc.CallOption) (*ReadinessResponse, error) {
	out := new(ReadinessResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/Readiness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adliveClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adliveClient) GetUserProfile(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*GetUserProfileResponse, error) {
	out := new(GetUserProfileResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/GetUserProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adliveClient) UpdateUserProfile(ctx context.Context, in *UserProfile, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/UpdateUserProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adliveClient) AddLocation(ctx context.Context, in *AddLocationRequest, opts ...grpc.CallOption) (*AddLocationResponse, error) {
	out := new(AddLocationResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/AddLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adliveClient) Locations(ctx context.Context, in *CommonPagingMessage, opts ...grpc.CallOption) (*ListLocationResponse, error) {
	out := new(ListLocationResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/Locations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adliveClient) RemoveLocation(ctx context.Context, in *RemoveLocationRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/RemoveLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adliveClient) ListArea(ctx context.Context, in *ListAreaRequest, opts ...grpc.CallOption) (*ListAreaResponse, error) {
	out := new(ListAreaResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/ListArea", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adliveClient) RemoveArea(ctx context.Context, in *RemoveAreaRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/RemoveArea", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adliveClient) AddScreen(ctx context.Context, in *AddScreenRequest, opts ...grpc.CallOption) (*AddScreenResponse, error) {
	out := new(AddScreenResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/AddScreen", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adliveClient) UpdateScreen(ctx context.Context, in *UpdateScreenRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/UpdateScreen", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adliveClient) ListScreen(ctx context.Context, in *ListScreenRequest, opts ...grpc.CallOption) (*ListScreenResponse, error) {
	out := new(ListScreenResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/ListScreen", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adliveClient) ListActivities(ctx context.Context, in *ListActivitiesRequest, opts ...grpc.CallOption) (*ListActivitiesResponse, error) {
	out := new(ListActivitiesResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/ListActivities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adliveClient) AddIssue(ctx context.Context, in *ReportIssueRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/AddIssue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adliveClient) ListVideo(ctx context.Context, in *CommonPagingMessage, opts ...grpc.CallOption) (*ListVideoResponse, error) {
	out := new(ListVideoResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/ListVideo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adliveClient) GetVideo(ctx context.Context, in *GetVideoRequest, opts ...grpc.CallOption) (*GetVideoResponse, error) {
	out := new(GetVideoResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/GetVideo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adliveClient) UploadVideo(ctx context.Context, in *Video, opts ...grpc.CallOption) (*UploadVideoResponse, error) {
	out := new(UploadVideoResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/UploadVideo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adliveClient) ListCampaign(ctx context.Context, in *CommonPagingMessage, opts ...grpc.CallOption) (*ListCampaignResponse, error) {
	out := new(ListCampaignResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/ListCampaign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adliveClient) GetCampaign(ctx context.Context, in *CampaignRequest, opts ...grpc.CallOption) (*CampaignResponse, error) {
	out := new(CampaignResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/GetCampaign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adliveClient) EditCampaign(ctx context.Context, in *CampaignDetail, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/pb.Adlive/EditCampaign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdliveServer is the server API for Adlive service.
type AdliveServer interface {
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	Liveness(context.Context, *LivenessRequest) (*LivenessResponse, error)
	ToggleReadiness(context.Context, *ToggleReadinessRequest) (*ToggleReadinessResponse, error)
	Readiness(context.Context, *ReadinessRequest) (*ReadinessResponse, error)
	// service: user
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	GetUserProfile(context.Context, *EmptyMessage) (*GetUserProfileResponse, error)
	UpdateUserProfile(context.Context, *UserProfile) (*CommonResponse, error)
	// service: location
	AddLocation(context.Context, *AddLocationRequest) (*AddLocationResponse, error)
	Locations(context.Context, *CommonPagingMessage) (*ListLocationResponse, error)
	RemoveLocation(context.Context, *RemoveLocationRequest) (*CommonResponse, error)
	// service: area
	ListArea(context.Context, *ListAreaRequest) (*ListAreaResponse, error)
	RemoveArea(context.Context, *RemoveAreaRequest) (*CommonResponse, error)
	// service: manageScreen
	AddScreen(context.Context, *AddScreenRequest) (*AddScreenResponse, error)
	UpdateScreen(context.Context, *UpdateScreenRequest) (*CommonResponse, error)
	ListScreen(context.Context, *ListScreenRequest) (*ListScreenResponse, error)
	// service: activities
	ListActivities(context.Context, *ListActivitiesRequest) (*ListActivitiesResponse, error)
	// service: Issue
	AddIssue(context.Context, *ReportIssueRequest) (*CommonResponse, error)
	// service: manageVideo
	ListVideo(context.Context, *CommonPagingMessage) (*ListVideoResponse, error)
	GetVideo(context.Context, *GetVideoRequest) (*GetVideoResponse, error)
	UploadVideo(context.Context, *Video) (*UploadVideoResponse, error)
	// service: Campaign
	ListCampaign(context.Context, *CommonPagingMessage) (*ListCampaignResponse, error)
	GetCampaign(context.Context, *CampaignRequest) (*CampaignResponse, error)
	EditCampaign(context.Context, *CampaignDetail) (*CommonResponse, error)
}

// UnimplementedAdliveServer can be embedded to have forward compatible implementations.
type UnimplementedAdliveServer struct {
}

func (*UnimplementedAdliveServer) Version(ctx context.Context, req *VersionRequest) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (*UnimplementedAdliveServer) Liveness(ctx context.Context, req *LivenessRequest) (*LivenessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Liveness not implemented")
}
func (*UnimplementedAdliveServer) ToggleReadiness(ctx context.Context, req *ToggleReadinessRequest) (*ToggleReadinessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToggleReadiness not implemented")
}
func (*UnimplementedAdliveServer) Readiness(ctx context.Context, req *ReadinessRequest) (*ReadinessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Readiness not implemented")
}
func (*UnimplementedAdliveServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAdliveServer) GetUserProfile(ctx context.Context, req *EmptyMessage) (*GetUserProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserProfile not implemented")
}
func (*UnimplementedAdliveServer) UpdateUserProfile(ctx context.Context, req *UserProfile) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserProfile not implemented")
}
func (*UnimplementedAdliveServer) AddLocation(ctx context.Context, req *AddLocationRequest) (*AddLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLocation not implemented")
}
func (*UnimplementedAdliveServer) Locations(ctx context.Context, req *CommonPagingMessage) (*ListLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Locations not implemented")
}
func (*UnimplementedAdliveServer) RemoveLocation(ctx context.Context, req *RemoveLocationRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveLocation not implemented")
}
func (*UnimplementedAdliveServer) ListArea(ctx context.Context, req *ListAreaRequest) (*ListAreaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListArea not implemented")
}
func (*UnimplementedAdliveServer) RemoveArea(ctx context.Context, req *RemoveAreaRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveArea not implemented")
}
func (*UnimplementedAdliveServer) AddScreen(ctx context.Context, req *AddScreenRequest) (*AddScreenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddScreen not implemented")
}
func (*UnimplementedAdliveServer) UpdateScreen(ctx context.Context, req *UpdateScreenRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateScreen not implemented")
}
func (*UnimplementedAdliveServer) ListScreen(ctx context.Context, req *ListScreenRequest) (*ListScreenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListScreen not implemented")
}
func (*UnimplementedAdliveServer) ListActivities(ctx context.Context, req *ListActivitiesRequest) (*ListActivitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListActivities not implemented")
}
func (*UnimplementedAdliveServer) AddIssue(ctx context.Context, req *ReportIssueRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddIssue not implemented")
}
func (*UnimplementedAdliveServer) ListVideo(ctx context.Context, req *CommonPagingMessage) (*ListVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVideo not implemented")
}
func (*UnimplementedAdliveServer) GetVideo(ctx context.Context, req *GetVideoRequest) (*GetVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideo not implemented")
}
func (*UnimplementedAdliveServer) UploadVideo(ctx context.Context, req *Video) (*UploadVideoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadVideo not implemented")
}
func (*UnimplementedAdliveServer) ListCampaign(ctx context.Context, req *CommonPagingMessage) (*ListCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCampaign not implemented")
}
func (*UnimplementedAdliveServer) GetCampaign(ctx context.Context, req *CampaignRequest) (*CampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCampaign not implemented")
}
func (*UnimplementedAdliveServer) EditCampaign(ctx context.Context, req *CampaignDetail) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditCampaign not implemented")
}

func RegisterAdliveServer(s *grpc.Server, srv AdliveServer) {
	s.RegisterService(&_Adlive_serviceDesc, srv)
}

func _Adlive_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adlive_Liveness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LivenessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).Liveness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/Liveness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).Liveness(ctx, req.(*LivenessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adlive_ToggleReadiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleReadinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).ToggleReadiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/ToggleReadiness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).ToggleReadiness(ctx, req.(*ToggleReadinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adlive_Readiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).Readiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/Readiness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).Readiness(ctx, req.(*ReadinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adlive_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adlive_GetUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).GetUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/GetUserProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).GetUserProfile(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adlive_UpdateUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserProfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).UpdateUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/UpdateUserProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).UpdateUserProfile(ctx, req.(*UserProfile))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adlive_AddLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).AddLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/AddLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).AddLocation(ctx, req.(*AddLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adlive_Locations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonPagingMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).Locations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/Locations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).Locations(ctx, req.(*CommonPagingMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adlive_RemoveLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).RemoveLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/RemoveLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).RemoveLocation(ctx, req.(*RemoveLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adlive_ListArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).ListArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/ListArea",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).ListArea(ctx, req.(*ListAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adlive_RemoveArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).RemoveArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/RemoveArea",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).RemoveArea(ctx, req.(*RemoveAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adlive_AddScreen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddScreenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).AddScreen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/AddScreen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).AddScreen(ctx, req.(*AddScreenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adlive_UpdateScreen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateScreenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).UpdateScreen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/UpdateScreen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).UpdateScreen(ctx, req.(*UpdateScreenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adlive_ListScreen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScreenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).ListScreen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/ListScreen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).ListScreen(ctx, req.(*ListScreenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adlive_ListActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).ListActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/ListActivities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).ListActivities(ctx, req.(*ListActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adlive_AddIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).AddIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/AddIssue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).AddIssue(ctx, req.(*ReportIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adlive_ListVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonPagingMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).ListVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/ListVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).ListVideo(ctx, req.(*CommonPagingMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adlive_GetVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).GetVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/GetVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).GetVideo(ctx, req.(*GetVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adlive_UploadVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Video)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).UploadVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/UploadVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).UploadVideo(ctx, req.(*Video))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adlive_ListCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonPagingMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).ListCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/ListCampaign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).ListCampaign(ctx, req.(*CommonPagingMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adlive_GetCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).GetCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/GetCampaign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).GetCampaign(ctx, req.(*CampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Adlive_EditCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CampaignDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdliveServer).EditCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Adlive/EditCampaign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdliveServer).EditCampaign(ctx, req.(*CampaignDetail))
	}
	return interceptor(ctx, in, info, handler)
}

var _Adlive_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Adlive",
	HandlerType: (*AdliveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Adlive_Version_Handler,
		},
		{
			MethodName: "Liveness",
			Handler:    _Adlive_Liveness_Handler,
		},
		{
			MethodName: "ToggleReadiness",
			Handler:    _Adlive_ToggleReadiness_Handler,
		},
		{
			MethodName: "Readiness",
			Handler:    _Adlive_Readiness_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Adlive_Login_Handler,
		},
		{
			MethodName: "GetUserProfile",
			Handler:    _Adlive_GetUserProfile_Handler,
		},
		{
			MethodName: "UpdateUserProfile",
			Handler:    _Adlive_UpdateUserProfile_Handler,
		},
		{
			MethodName: "AddLocation",
			Handler:    _Adlive_AddLocation_Handler,
		},
		{
			MethodName: "Locations",
			Handler:    _Adlive_Locations_Handler,
		},
		{
			MethodName: "RemoveLocation",
			Handler:    _Adlive_RemoveLocation_Handler,
		},
		{
			MethodName: "ListArea",
			Handler:    _Adlive_ListArea_Handler,
		},
		{
			MethodName: "RemoveArea",
			Handler:    _Adlive_RemoveArea_Handler,
		},
		{
			MethodName: "AddScreen",
			Handler:    _Adlive_AddScreen_Handler,
		},
		{
			MethodName: "UpdateScreen",
			Handler:    _Adlive_UpdateScreen_Handler,
		},
		{
			MethodName: "ListScreen",
			Handler:    _Adlive_ListScreen_Handler,
		},
		{
			MethodName: "ListActivities",
			Handler:    _Adlive_ListActivities_Handler,
		},
		{
			MethodName: "AddIssue",
			Handler:    _Adlive_AddIssue_Handler,
		},
		{
			MethodName: "ListVideo",
			Handler:    _Adlive_ListVideo_Handler,
		},
		{
			MethodName: "GetVideo",
			Handler:    _Adlive_GetVideo_Handler,
		},
		{
			MethodName: "UploadVideo",
			Handler:    _Adlive_UploadVideo_Handler,
		},
		{
			MethodName: "ListCampaign",
			Handler:    _Adlive_ListCampaign_Handler,
		},
		{
			MethodName: "GetCampaign",
			Handler:    _Adlive_GetCampaign_Handler,
		},
		{
			MethodName: "EditCampaign",
			Handler:    _Adlive_EditCampaign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func (m *VersionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VersionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VersionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func (m *VersionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VersionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VersionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintService(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LivenessRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LivenessRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LivenessRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func (m *LivenessResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LivenessResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LivenessResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintService(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ToggleReadinessRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ToggleReadinessRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ToggleReadinessRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func (m *ToggleReadinessResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ToggleReadinessResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ToggleReadinessResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintService(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ReadinessRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReadinessRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReadinessRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func (m *ReadinessResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReadinessResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReadinessResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintService(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintService(dAtA []byte, offset int, v uint64) int {
	offset -= sovService(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *VersionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *VersionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *LivenessRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *LivenessResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ToggleReadinessRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ToggleReadinessResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ReadinessRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ReadinessResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovService(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozService(x uint64) (n int) {
	return sovService(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *VersionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VersionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VersionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VersionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VersionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VersionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LivenessRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LivenessRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LivenessRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LivenessResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LivenessResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LivenessResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ToggleReadinessRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ToggleReadinessRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ToggleReadinessRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ToggleReadinessResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ToggleReadinessResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ToggleReadinessResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReadinessRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReadinessRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReadinessRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReadinessResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReadinessResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReadinessResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipService(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowService
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthService
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupService
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthService
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthService        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowService          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupService = fmt.Errorf("proto: unexpected end of group")
)
