// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types.proto

package pb

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *EmptyMessage) Validate() error {
	return nil
}
func (this *UserProfile) Validate() error {
	return nil
}
func (this *Area) Validate() error {
	return nil
}
func (this *ScreenActivity) Validate() error {
	return nil
}
func (this *ScreenActivities) Validate() error {
	for _, item := range this.Data {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
			}
		}
	}
	return nil
}
func (this *ScreenInfo) Validate() error {
	return nil
}
func (this *Video) Validate() error {
	return nil
}
func (this *Videos) Validate() error {
	for _, item := range this.Data {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
			}
		}
	}
	return nil
}
func (this *AdSetBasic) Validate() error {
	return nil
}
func (this *AdSet) Validate() error {
	for _, item := range this.Data {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
			}
		}
	}
	return nil
}
func (this *AdSet_Video) Validate() error {
	return nil
}
func (this *Campaign) Validate() error {
	if this.AdSet != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.AdSet); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("AdSet", err)
		}
	}
	return nil
}
func (this *CampaignRule) Validate() error {
	return nil
}
func (this *CampaignDetail) Validate() error {
	if this.AdSet != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.AdSet); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("AdSet", err)
		}
	}
	if this.CampaignRule != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CampaignRule); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CampaignRule", err)
		}
	}
	return nil
}
